### ISSUE TITLE
what is ./swl-websocket-server in the user-root on springrts.com?

### ISSUE THREAD

**Issue by abma** [springweblobby/swl-qt#15]
where is the source-code?

is it still needed?

i'm asking because it has an open tcp-port on the server.

any docs about it?

**Comment by db81** [comment]
It's a tiny websockets proxy server to let the new React weblobby connect to the lobby server from browser, which is useful for testing. The source can be seen at https://code.google.com/p/springweblobby/source/browse/branches/websockets/server/src/chat_server.hpp. If you're worried, I can move it to my VPS since it's incosequential where it runs.

**Comment by db81** [comment]
By "the new React weblobby" I mean http://weblobby.springrts.com/reactjs/index.html.

**Comment by abma** [comment]
does this mean, there are currently 3 different springweblobbies?

http://weblobby.springrts.com/java/site/
http://weblobby.springrts.com/reactjs/index.html
https://googledrive.com/host/0Bys6k7VMCRfUZ0N5MGJXR1pRV2M/

hu? why?

can you please remove/drop the unmaintained?

**Comment by abma** [comment]
also there already exists http://webchat.springrts.com/

**Comment by abma** [comment]
>  which is useful for testing.

if its for testing only, does it need to run 24/7?

**Comment by db81** [comment]
It's just more convenient because you don't have to start it every time and you can forward people to the webpage for a live demonstration of sorts. I've moved it to a VPS where it can run without bothering anyone.

> can you please remove/drop the unmaintained?

Sure, I'll drop the Java one. The other 2 are the current iteration of swl and reactswl which is a work in progress.

> we have more lobbies than users :-|

The bane of open source projects :P

**Comment by abma** [comment]
thanks! :)
